### ISSUE TITLE
Storybook > Build Verification > Version 1.0.2

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#638]
**Storybook > Build Verification > Version 1.1.8**

https://github.com/Wai-Technologies/raaghu-react/releases/tag/1.1.8(s) 

![Image](https://github.com/user-attachments/assets/b329d6de-beb2-43ed-be63-878cfb9fe5ca)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Sr.No | Task ID | Status
-- | -- | --
1 | Updated   Staging Action : "Raaghu Design System Storybook Deployment"   by @Shankar1006 in #617 |  
2 | Action   Changes : Updated Environment for Staging Deployment by @Shankar1006 in #619 |  
3 | Resolved   Bug 539 : Resolved Storybook Components Issues by @pravinwaghmare23 in #580 |  
4 | Resolved   Bug 511 and 568 : Storybook > Elements > Feed > Select dark theme   star color is not change And Storybook > Elements > Widget Portal >   Incorrect text by @pravinwaghmare23 in #581 |  
5 | Resolved   Bug 569 and 582 : Small and Large Mobile View Language Pop Up Is Not Display   Proper , Color Code Is Invalid. by @ashoksinarewai in #583 |  
6 | Resolved   Bug 448, 570, 472 and 589 : Issue on Visual Setting Component, Hand Cursor   Issue on Icons, Issues on Collapsible Container and Assistance Component   by @AkshayPotphode in #587 |  
7 | Resolved   Bug 586 and 594 : Dark Theme Text Is Not Display Proper And Dark Theme   Selected Value Is Not Visible Proper by @ashoksinarewai in #597 |  
8 | Resolved   Bug 567 and 574 : Storybook > Components > Product List > Images   alignment is not proper And Component > Edition New Basic : Validation   missing for Edition Name. No error message if its kept emptyoved by @pravinwaghmare23 in #599 |  
9 | Resolved   Bug 563 : After Submitting Field Is Not Clear by @ashoksinarewai in #600 |  
10 | Completed   Task 601 : Implement Different Divider by @ashoksinarewai in #607 |  
11 | Completed   Task 591 : Implement Different Types Buttons by @prakashmhaske in #608 |  
12 | Resolved   Bug 526 : Changes Made for the Stacked Chart Views by @BhakareAbhishek in #613 |  
13 | Completed   Task 612 : Add the New Type of Breadcrumb by @BhakareAbhishek in #623 |  
14 | Resolved   Bug 628 : Label Is CICD Instead Of Ci/CD by @abhijeetjawale1 in #631 |  
15 | Resolved   Bug 629 : App Details > Incorrect Word by @abhijeetjawale1 in #632 |  
16 | Resolved   Bug 630 : Banner > Space is missing between word News and ! by @abhijeetjawale1 in #633 |  
17 | Staging   : Merge Changes from Development to Staging Branch by @Ketan-Khalate in #634 |  
18 | Resolved   Bug : Build Issue by @Ketan-Khalate in #636 |  
19 | Staging   : Merge Changes from Development to Staging Branch by @Ketan-Khalate in #637 |  

</body>

</html>

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


Sr.No | Bug Title | Bud/Task ID | Status | Worked On
-- | -- | -- | -- | --
1 | Storybook   >Elements>Feed> Select dark theme star color is not change. · Issue   #511 · Wai-Technologies/raaghu-react (github.com) | 511 | Already closed | Pravin
2 | Storybook   >Elements>Widget Portal >Incorrect text · Issue #568 ·   Wai-Technologies/raaghu-react (github.com) | 568 | Closed | Pravin
3 | Storybook   >Components>Top Navigation With Search>Small & large mobile view   language pop up is not display proper. · Issue #569 ·   Wai-Technologies/raaghu-react (github.com) | 569 | Closed | Ashok
4 | Storybook   >Charts> Doughnut Chart>Color code is invalid. · Issue #582 ·   Wai-Technologies/raaghu-react (github.com) | 582 | Closed | Ashok
5 | Storybook   > Components >Visual Setting > Default >Alignment issue   Subheader, Menu, Footer, click on dropdown chevron is not upward and downward   · Issue #448 · Wai-Technologies/raaghu-react (github.com) | 448 | Closed | Akshay
6 | Storybook   >Elements>Breadcrumb > Hand cursor is expected · Issue #570 ·   Wai-Technologies/raaghu-react (github.com) | 570 | Reopen | Akshay
7 | Add newly   designed and existing updated components from A. S · Issue #472 ·   Wai-Technologies/raaghu-react (github.com) | 472 | Closed | Akshay
8 | Storybook   > Component > Assistance > Docs > Overlap button on form content.   · Issue #589 · Wai-Technologies/raaghu-react (github.com) | 589 | Closed | Akshay
9 | Storybook>Elements   >Select List > Dark theme selected value is not visible proper. · Issue   #594 · Wai-Technologies/raaghu-react (github.com) | 594 | Closed | Ashok
10 | Storybook   >Components>Product List > Images alignment is not proper. · Issue   #567 · Wai-Technologies/raaghu-react (github.com) | 567 | Reopen | Pravin
11 | Design   System > Component >Edition New Basic : Validation missing for Edition   Name. No error message if its kept empty · Issue #574 ·   Wai-Technologies/raaghu-react (github.com) | 574 | Closed | Pravin
12 | Storybook   >Components>Theme New > Invalid placeholder · Issue #563 ·   Wai-Technologies/raaghu-react (github.com) | 563 | Already closed | Ashok
13 | Design   System > Implement different Divide bar · Issue #601 ·   Wai-Technologies/raaghu-react (github.com) | 601 | Closed | Ashok
14 | Design   System > Implement different types Buttons · Issue #591 ·   Wai-Technologies/raaghu-react (github.com) | 591 | Reopen | Prakash
15 | Storybook   >Charts>Stacked Chart> Small and large mobile view, Tablet, reset   viewport is not display proper. · Issue #526 · Wai-Technologies/raaghu-react   (github.com) | 526 | Already closed | Abhishek
16 | Design   System > Implement different breadcrumbs · Issue #612 ·   Wai-Technologies/raaghu-react (github.com) | 612 | Closed | Abhishek
17 | Design   System > Label is CICD instead of Ci/Cd · Issue #628 ·   Wai-Technologies/raaghu-react (github.com) | 628 | Closed | Abhijeet
18 | Design   System > Elements > Alert > App Details : Incorrect Word · Issue   #629 · Wai-Technologies/raaghu-react (github.com) | 629 | Closed | Abhijeet
19 | Design   System : Elements > Banner : Space is missing between word News and ! ·   Issue #630 · Wai-Technologies/raaghu-react (github.com) | 630 | Closed | Abhijeet
20 | Storybook   Issues : Components · Issue #539 · Wai-Technologies/raaghu-react (github.com) | 539 | Reopen | Pravin
21 | Storybook   >Components>Datatable> Action Button on Left Side> Action modal   is opening but on mouse hover edit is hide · Raaghu Design System Storybook -   React (github.com) | 509 | Closed | Abhishek
  |   |   |   |  
  |   |   |   |  



</body>

</html>
